version: 2

aliases:
  setup_env: &setup-env
    docker:
      - image: circleci/node:8.10.0
  save_cache: &save-cache
    key: v9-dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      # explicitly list each package node_modules
      - packages/core/node_modules
      - packages/datetime/node_modules
      - packages/docs-app/node_modules
      - packages/docs-data/node_modules
      - packages/docs-theme/node_modules
      - packages/icons/node_modules
      - packages/karma-build-scripts/node_modules
      - packages/labs/node_modules
      - packages/landing-app/node_modules
      - packages/node-build-scripts/node_modules
      - packages/select/node_modules
      - packages/table/node_modules
      - packages/table-dev-app/node_modules
      - packages/test-commons/node_modules
      - packages/test-react15/node_modules
      - packages/timezone/node_modules
      - packages/tslint-config/node_modules
      - packages/webpack-build-scripts/node_modules
  restore_cache: &restore-cache
    keys:
      - v9-dependency-cache-{{ checksum "yarn.lock" }}
      - v9-dependency-cache-
  build_dirs: &build-dirs
    root: '.'
    paths:
      # directories to persist to workspace
      - packages/*/dist
      - packages/*/lib
      - packages/*/src/generated
  reports_path: &reports-path
    path: ./reports

jobs:
  install-dependencies:
    <<: *setup-env
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache: *restore-cache
      - run: yarn --frozen-lockfile
      - run: npm rebuild node-sass
      - save_cache: *save-cache
      - persist_to_workspace:
          root: '.'
          paths:
            - yarn.lock

  compile:
    <<: *setup-env
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache: *restore-cache
      - run: yarn compile
      - persist_to_workspace: *build-dirs

  lint:
    <<: *setup-env
    environment:
      JUNIT_REPORT_PATH: reports
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache: *restore-cache
      - run: mkdir -p ./reports/tslint ./reports/stylelint
      - run: yarn compile --scope "@blueprintjs/tslint-config"
      - run: yarn lint
      - store_test_results: *reports-path
      - store_artifacts: *reports-path

  dist:
    <<: *setup-env
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache: *restore-cache
      - run: yarn dist:libs
      - run: yarn dist:apps
      # skip dist:docs because we do not publish GitHub Pages from CI
      - persist_to_workspace: *build-dirs

  test-react-16: &run-tests
    docker:
      - image: circleci/node:8.10.0-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    environment:
      JUNIT_REPORT_PATH: reports
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache: *restore-cache
      - run: mkdir ./reports
      - run:
          command: |
              case $CIRCLE_NODE_INDEX in \
              0) yarn lerna run --parallel test:pre ;; \
              1) yarn lerna run --parallel test:iso ;; \
              2) yarn lerna run --parallel test:karma ;; \
              esac
          when: always
      - store_test_results: *reports-path
      - store_artifacts: *reports-path

  test-react-15:
    # copy test-react16 and override environment
    <<: *run-tests
    environment:
      JUNIT_REPORT_PATH: reports
      REACT: 15 # use React 15 for this job

  deploy-preview:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - store_artifacts:
          path: docs
      - store_artifacts:
          path: packages/docs-app/dist
      - store_artifacts:
          path: packages/landing-app/dist
      - store_artifacts:
          path: packages/table-dev-app/dist
      - run:
          name: Submit Github comment with links to built artifacts
          command: ./scripts/submit-preview-comment

  deploy-npm:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache: *restore-cache
      - run: ./scripts/publish-npm-semver-tagged

workflows:
  version: 2
  compile_lint_test_dist_deploy:
    jobs:
      - install-dependencies
      - compile:
          requires: [install-dependencies]
      - lint:
          requires: [install-dependencies]
      - dist:
          requires: [compile]
      - test-react-15:
          requires: [compile]
      - test-react-16:
          requires: [compile]
      - deploy-preview:
          requires: [dist]
      - deploy-npm:
          requires: [dist, lint, test-react15, test-react16]
          filters:
            branches:
              only:
                - develop
                - /^release\/.*/
